### ISSUE TITLE
Can't run this more than once

### ISSUE THREAD

**Issue by ghost** [jkingsman/plex-shared-library-downloader#1]
The first time the bookmarklet code is injected it's run automatically and the downoad will succeed. For the second download it will fail. This is because the javascript code inside the extension does not have access to the variable scope of the page.

`plxDwnld`(in [content_script.js](https://github.com/jkingsman/plex-shared-library-downloader/blob/master/src/js/content_script.js#L5)) will be undefined all the time, so `if (typeof plxDwnld == 'undefined')` will always evaluate to true. It will then again include the bookmarklet code. This will run automatically, but fails because from the point of view of _that_ code `const plxDwnld` already exists.

This results in this error:
```
Uncaught SyntaxError: Identifier 'plxDwnld' has already been declared
    at bookmarklet.js?ts=1586454424:1
(anonymous) @ bookmarklet.js?ts=1586454424:1
```

**Comment by ghost** [comment]
I've [semi-fixed](https://github.com/piplongrun/piplongrun.github.io/blob/master/plxdwnld/bookmarklet.js#L13-L15) it on the bookmarklet's side, but the extension will still insert the javascript code every time the download button is clicked.

**Comment by jkingsman** [comment]
Oh well that's dumb of me 😅 Will poke at; thanks for the catch!

**Comment by jkingsman** [comment]
Ugh chrome extension permissions always crush my hopes and dreams. This is stable, though terribly inefficient and loading your site more than it should.

Probably gonna poke at it this weekend.

**Comment by ghost** [comment]
Haha, I looked at the code and the issue this afternoon thinking it would be an easy fix... 3 hours later... Pulling my hair out because of how Chrome extensions work :-D

**Comment by jkingsman** [comment]
Yeah they have a tendency to do that haha. Push comes to shove I'll just leave it injecting multiples. It's not efficient, but I believe your site is backed by GitHub, right? i.e. me loading things more than it should isn't an issue that would cost you

**Comment by ghost** [comment]
Hi! Yep, this is hosted on Github, so the couple extra requests do not really matter. I might check the cache busting "?ts=" at the end of the URL, because that isn't even really neccesary. With this removed or shortened the file will probably be loaded from the browser cache after the first load.

**Comment by juliangaal** [comment]
Same issue with the plugins from [here](https://sharedriches.com/plex-scripts/piplongrun/). What's the general state of this project?

**Comment by jkingsman** [comment]
It looks like that site is just rehosting Pip's code. It seems like Pip has dropped off the web, or something approximating that. I've only had casual correspondence with him. His code is MIT licensed, so anyone is free to edit/rehost with attribution, but this project is just built on top of it and I don't have any power over Pip's original code (and its functioning or non-functioning) beyond my usage of it in this Chrome extension.

Since that might or might not have been what you were asking, to answer your direct question, this project (the Chrome extension) is under bugfix-only development as one of a number of side projects I juggle outside my dayjob. Happy to accept quality PRs for improvement, and open to a maintainer taking over if they feel passionately (not that there's much to maintain).

**Comment by juliangaal** [comment]
ok, thanks for the update and for your work!
