### ISSUE TITLE
The download button does not show up

### ISSUE THREAD

**Issue by JustinSaysRadio** [jkingsman/plex-shared-library-downloader#12]
The download button has not showed up ever since a few days ago.

**Comment by CyberPoison** [comment]
Yeah me too.

**Comment by jkingsman** [comment]
Sorry to hear that -- I'm traveling and with family right now, so can't look at this immediately. I'll do my best to set aside some time over the next few weeks, but holidays loom and my time is tight.

**Comment by jkingsman** [comment]
Hey folks -- this library has unfortunately become such a cat and mouse game of UI + download code that maintaining it is becoming a workload I can't keep up with. I've unpublished the Google store listing (rife with negative reviews due to the deteriorating functionality heh), and am going to suspend working on this, most likely for the long term. Super open to someone forking the codebase though! This was always mostly Pip Longrun's work anyway, so I have no clinginess to ownership.

Thanks for all the issue reports and interest in keeping this alive! So long, and thanks for all the fish.
